<?php

namespace App\Constants;

class Logging
{
    public const ACCOUNTANT_API_REFRESH_ACCESS_TOKEN_REQUEST = 'ACCOUNTANT_API_REFRESH_ACCESS_TOKEN_REQUEST';
    public const ACCOUNTANT_API_REFRESH_ACCESS_TOKEN_REQUEST_FAIL = 'ACCOUNTANT_API_REFRESH_ACCESS_TOKEN_REQUEST_FAIL';
    public const ACCOUNTANT_REFRESH_ACCESS_TOKEN_FAIL = 'ACCOUNTANT_REFRESH_ACCESS_TOKEN_FAIL';
    public const ACCOUNTANT_API_GET_PRODUCTS_REQUEST = 'ACCOUNTANT_API_GET_PRODUCTS_REQUEST';
    public const ACCOUNTANT_API_GET_PRODUCTS_REQUEST_FAIL = 'ACCOUNTANT_API_GET_PRODUCTS_REQUEST_FAIL';
    public const ACCOUNTANT_PRODUCT_SYNC_COMMAND_FAIL = 'ACCOUNTANT_PRODUCT_SYNC_COMMAND_FAIL';
    public const ACCOUNTANT_PRODUCT_SYNC_JOB_FAIL = 'ACCOUNTANT_PRODUCT_SYNC_JOB_FAIL';
    public const ACCOUNTANT_API_GET_PRODUCTS_BY_STORAGE_REQUEST = 'ACCOUNTANT_API_GET_PRODUCTS_BY_STORAGE_REQUEST';
    public const ACCOUNTANT_API_GET_PRODUCTS_BY_STORAGE_REQUEST_FAIL = 'ACCOUNTANT_API_GET_PRODUCTS_BY_STORAGE_REQUEST_FAIL';
    public const ACCOUNTANT_PRODUCTS_BY_STORAGE_FAIL = 'ACCOUNTANT_PRODUCTS_BY_STORAGE_FAIL';
}
