<?php

namespace App\Constants;

class Logging
{
    public const ACCOUNTANT_API_REFRESH_ACCESS_TOKEN_REQUEST = 'ACCOUNTANT_API_REFRESH_ACCESS_TOKEN_REQUEST';
    public const ACCOUNTANT_API_REFRESH_ACCESS_TOKEN_REQUEST_FAIL = 'ACCOUNTANT_API_REFRESH_ACCESS_TOKEN_REQUEST_FAIL';
}
